import type { SidebarGroup } from './components/DocsShell'

export interface ComponentEntry {
  label: string
  slug: string
  comingSoon?: boolean
}

export const COMPONENTS: ComponentEntry[] = [
  { label: 'Button', slug: 'button' },
  { label: 'Badge', slug: 'badge' },
  { label: 'Chip', slug: 'chip' },
  { label: 'Card', slug: 'card' },
  { label: 'Avatar', slug: 'avatar' },
  { label: 'Separator', slug: 'separator' },
  { label: 'Input', slug: 'input' },
  { label: 'Textarea', slug: 'textarea' },
  { label: 'Select', slug: 'select' },
  { label: 'Checkbox', slug: 'checkbox' },
  { label: 'Radio', slug: 'radio' },
  { label: 'Switch', slug: 'switch' },
  { label: 'Toggle', slug: 'toggle' },
  { label: 'Label', slug: 'label' },
  { label: 'Slider', slug: 'slider' },
  { label: 'Toggle group', slug: 'toggle-group' },
  { label: 'Tabs', slug: 'tabs' },
  { label: 'Collapsible', slug: 'collapsible' },
  { label: 'Dialog', slug: 'dialog' },
  { label: 'Alert dialog', slug: 'alert-dialog' },
  { label: 'Portal', slug: 'portal' },
  { label: 'Visually hidden', slug: 'visually-hidden' },
  { label: 'Slot', slug: 'slot' },
  { label: 'Kbd', slug: 'kbd' },
  { label: 'Code', slug: 'code' },
  { label: 'Mark', slug: 'mark' },
  { label: 'Blockquote', slug: 'blockquote' },
  { label: 'Number input', slug: 'number-input' },
  { label: 'Pin input', slug: 'pin-input' },
  { label: 'Rating', slug: 'rating' },
  { label: 'Hover card', slug: 'hover-card' },
  { label: 'Context menu', slug: 'context-menu' },
  { label: 'Drawer', slug: 'drawer' },
  { label: 'Scroll area', slug: 'scroll-area' },
  { label: 'Carousel', slug: 'carousel' },
  { label: 'Timeline', slug: 'timeline' },
  { label: 'Tree', slug: 'tree' },
  { label: 'Combobox', slug: 'combobox' },
  { label: 'Multi select', slug: 'multi-select' },
  { label: 'File upload', slug: 'file-upload' },
  { label: 'Form', slug: 'form' },
  { label: 'Date picker', slug: 'date-picker' },
  { label: 'Sheet', slug: 'sheet' },
  { label: 'Dropdown menu', slug: 'dropdown' },
  { label: 'Popover', slug: 'popover' },
  { label: 'Tooltip', slug: 'tooltip' },
  { label: 'Command palette', slug: 'command' },
  { label: 'Toast', slug: 'toast' },
  { label: 'Alert', slug: 'alert' },
  { label: 'Progress', slug: 'progress' },
  { label: 'Spinner', slug: 'spinner' },
  { label: 'Skeleton', slug: 'skeleton' },
  { label: 'Empty state', slug: 'empty-state' },
  { label: 'Breadcrumbs', slug: 'breadcrumbs' },
  { label: 'Pagination', slug: 'pagination' },
  { label: 'Stepper', slug: 'stepper' },
  { label: 'Accordion', slug: 'accordion' },
  { label: 'Navbar', slug: 'navbar' },
  { label: 'Sidebar', slug: 'sidebar' },
  { label: 'Data grid', slug: 'data-grid' },
  { label: 'Table', slug: 'table' },
  { label: 'Charts', slug: 'charts' },
  { label: 'Layout primitives', slug: 'layout' },
  { label: 'Motion utilities', slug: 'motion-utilities' },
]

const item = (label: string, slug: string) => {
  const entry = COMPONENTS.find((c) => c.slug === slug)
  return { label, to: `/components/${slug}`, ...(entry?.comingSoon ? { chip: 'soon' } : {}) }
}

/** The 16 series types shown on /charts/catalogue; ids match the tile anchors. */
export const CATALOGUE_SERIES = [
  { label: 'Line', id: 'line' },
  { label: 'Area · stacked', id: 'area-stacked' },
  { label: 'Step', id: 'step' },
  { label: 'Bar · horizontal', id: 'bar-horizontal' },
  { label: 'Bar · stacked', id: 'bar-stacked' },
  { label: 'Composed', id: 'composed' },
  { label: 'Scatter', id: 'scatter' },
  { label: 'Candlestick', id: 'candlestick' },
  { label: 'Pie', id: 'pie' },
  { label: 'Radar', id: 'radar' },
  { label: 'Funnel', id: 'funnel' },
  { label: 'Waterfall', id: 'waterfall' },
  { label: 'Treemap', id: 'treemap' },
  { label: 'Gauge · arc', id: 'gauge-arc' },
  { label: 'Sparkline', id: 'sparkline' },
  { label: 'Heatmap · Donut', id: 'heatmap-donut' },
]

const CHART_PAGE_SUB = [
  { label: 'Anatomy', id: 'anatomy' },
  { label: 'Composition', id: 'composition' },
  { label: 'Variants', id: 'variants' },
  { label: 'Motion', id: 'motion' },
  { label: 'Accessibility', id: 'accessibility' },
  { label: 'API', id: 'api' },
]

export const DOCS_SIDEBAR: SidebarGroup[] = [
  {
    title: 'Getting started',
    items: [
      { label: 'Introduction', to: '/' },
      ...(import.meta.env.DEV
        ? [{ label: 'Playground', to: '/playground', chip: 'LIVE' }]
        : []),
      { label: 'Installation', to: '/docs/installation' },
      { label: 'Usage', to: '/docs/usage' },
      { label: 'Customization', to: '/docs/customization', chip: 'NEW' },
      { label: 'CLI', to: '/docs/installation#step-1' },
      { label: 'Theming', to: '/docs/tokens' },
      { label: 'Dark mode', to: '/accents' },
      { label: 'Motion system', to: '/docs/motion' },
      { label: 'Accessibility', to: '/docs/motion#reduced' },
    ],
  },
  {
    title: 'Frameworks',
    items: [
      { label: 'Next.js', to: '/docs/installation#frameworks' },
      { label: 'Vite', to: '/docs/installation#frameworks-vite' },
      { label: 'Remix', to: '/docs/installation#frameworks-remix' },
      { label: 'Astro', to: '/docs/installation#frameworks-astro' },
    ],
  },
  {
    title: 'Components',
    items: [{ label: `All components (${COMPONENTS.length})`, to: '/components' }],
    sections: [
      {
        title: 'Primitives',
        items: [
          { label: 'Overview', to: '/components#primitives' },
          item('Button', 'button'), item('Badge', 'badge'), item('Chip', 'chip'),
          item('Card', 'card'), item('Avatar', 'avatar'), item('Separator', 'separator'),
          { label: 'Kbd', to: '/components/kbd', chip: 'NEW' },
          { label: 'Code', to: '/components/code', chip: 'NEW' },
          { label: 'Mark', to: '/components/mark', chip: 'NEW' },
          { label: 'Blockquote', to: '/components/blockquote', chip: 'NEW' },
          { label: 'Portal', to: '/components/portal', chip: 'NEW' },
          { label: 'Visually hidden', to: '/components/visually-hidden', chip: 'NEW' },
          { label: 'Slot', to: '/components/slot', chip: 'NEW' },
        ],
      },
      {
        title: 'Forms',
        items: [
          { label: 'Overview', to: '/components#forms' },
          item('Label', 'label'),
          item('Input', 'input'), item('Textarea', 'textarea'), item('Select', 'select'),
          { label: 'Combobox', to: '/components/combobox', chip: 'NEW' },
          { label: 'Multi select', to: '/components/multi-select', chip: 'NEW' },
          { label: 'Number input', to: '/components/number-input', chip: 'NEW' },
          { label: 'Pin input', to: '/components/pin-input', chip: 'NEW' },
          item('Checkbox', 'checkbox'), item('Radio', 'radio'), item('Switch', 'switch'),
          item('Toggle', 'toggle'),
          { label: 'Rating', to: '/components/rating', chip: 'NEW' },
          { label: 'File upload', to: '/components/file-upload', chip: 'NEW' },
          { label: 'Date picker', to: '/components/date-picker', chip: 'NEW' },
          item('Slider', 'slider'), item('Toggle group', 'toggle-group'), item('Tabs', 'tabs'),
          item('Collapsible', 'collapsible'),
          { label: 'Form', to: '/components/form', chip: 'NEW' },
        ],
      },
      {
        title: 'Overlays',
        items: [
          { label: 'Overview', to: '/components#overlays' },
          item('Dialog', 'dialog'),
          { label: 'Alert dialog', to: '/components/alert-dialog', chip: 'NEW' },
          { label: 'Drawer', to: '/components/drawer', chip: 'NEW' },
          item('Sheet', 'sheet'), item('Dropdown menu', 'dropdown'),
          { label: 'Context menu', to: '/components/context-menu', chip: 'NEW' },
          item('Popover', 'popover'), item('Tooltip', 'tooltip'),
          { label: 'Hover card', to: '/components/hover-card', chip: 'NEW' },
          { label: 'Command palette', to: '/components/command', chip: 'NEW' },
        ],
      },
      {
        title: 'Feedback',
        items: [
          { label: 'Overview', to: '/components#feedback' },
          item('Toast', 'toast'), item('Alert', 'alert'), item('Progress', 'progress'),
          item('Spinner', 'spinner'), item('Skeleton', 'skeleton'), item('Empty state', 'empty-state'),
        ],
      },
      {
        title: 'Navigation',
        items: [
          { label: 'Overview', to: '/components#navigation' },
          {
            label: 'Navbar', to: '/components/navbar',
            sub: [
              { label: 'Anatomy', id: 'anatomy' },
              { label: 'Composition', id: 'composition' },
              { label: 'Variants', id: 'variants' },
              { label: 'Accessibility', id: 'accessibility' },
              { label: 'API', id: 'api' },
            ],
          },
          {
            label: 'Sidebar', to: '/components/sidebar',
            sub: [
              { label: 'Anatomy', id: 'anatomy' },
              { label: 'Composition', id: 'composition' },
              { label: 'Variants', id: 'variants' },
              { label: 'Collapse behavior', id: 'collapse-behavior' },
              { label: 'Accessibility', id: 'accessibility' },
              { label: 'API', id: 'api' },
            ],
          },
          item('Breadcrumbs', 'breadcrumbs'), item('Pagination', 'pagination'),
          item('Stepper', 'stepper'), item('Accordion', 'accordion'),
          { label: 'Tree', to: '/components/tree', chip: 'NEW' },
          { label: 'Timeline', to: '/components/timeline', chip: 'NEW' },
          { label: 'Carousel', to: '/components/carousel', chip: 'NEW' },
          { label: 'Scroll area', to: '/components/scroll-area', chip: 'NEW' },
        ],
      },
      {
        title: 'Data',
        items: [
          { label: 'Overview', to: '/components#data' },
          {
            label: 'Data grid', to: '/components/data-grid',
            sub: [
              { label: 'Anatomy', id: 'anatomy' },
              { label: 'Composition', id: 'composition' },
              { label: 'Columns', id: 'columns' },
              { label: 'Filtering & sort', id: 'filtering' },
              { label: 'Selection & editing', id: 'selection' },
              { label: 'Grouping & tree', id: 'grouping' },
              { label: 'Scale & state', id: 'scale' },
              { label: 'Export & types', id: 'export' },
              { label: 'API', id: 'api' },
            ],
          },
          {
            label: 'Table', to: '/components/table',
            sub: [
              { label: 'Anatomy', id: 'anatomy' },
              { label: 'Composition', id: 'composition' },
              { label: 'Row variants & density', id: 'row-variants' },
              { label: 'Cell variants', id: 'cell-variants' },
              { label: 'Sticky header & scroll', id: 'sticky' },
              { label: 'Accessibility', id: 'accessibility' },
              { label: 'API', id: 'api' },
            ],
          },
        ],
      },
      {
        title: 'Charts',
        items: [
          { label: 'Overview', to: '/charts', chip: 'NEW' },
          { label: 'Catalogue', to: '/charts/catalogue', sub: CATALOGUE_SERIES },
          {
            label: 'Line', to: '/docs/charts/line',
            sub: [
              { label: 'Basics', id: 'basics' },
              { label: 'Area & stacking', id: 'area-stacking' },
              { label: 'Tooltip & crosshair', id: 'tooltip-crosshair' },
              { label: 'Draw-in motion', id: 'draw-in-motion' },
              { label: 'Components & API', id: 'components-api' },
            ],
          },
          { label: 'Area', to: '/docs/charts/area', sub: CHART_PAGE_SUB },
          { label: 'Bar', to: '/docs/charts/bar', sub: CHART_PAGE_SUB },
          { label: 'Pie & Donut', to: '/docs/charts/pie-donut', sub: CHART_PAGE_SUB },
          { label: 'Scatter', to: '/docs/charts/scatter', sub: CHART_PAGE_SUB },
          { label: 'Candlestick', to: '/docs/charts/candle', sub: CHART_PAGE_SUB },
          { label: 'Radar', to: '/docs/charts/radar', sub: CHART_PAGE_SUB },
          { label: 'Funnel', to: '/docs/charts/funnel', sub: CHART_PAGE_SUB },
          { label: 'Waterfall', to: '/docs/charts/waterfall', sub: CHART_PAGE_SUB },
          { label: 'Treemap', to: '/docs/charts/treemap', sub: CHART_PAGE_SUB },
          { label: 'Heatmap', to: '/docs/charts/heatmap', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Gauge', to: '/docs/charts/gauge', sub: CHART_PAGE_SUB },
          { label: 'Sparkline', to: '/docs/charts/sparkline', sub: CHART_PAGE_SUB },
          { label: 'Bullet', to: '/docs/charts/bullet', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Lollipop', to: '/docs/charts/lollipop', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Dumbbell', to: '/docs/charts/dumbbell', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Slope', to: '/docs/charts/slope', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Radial bar', to: '/docs/charts/radial-bar', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Parallel coordinates', to: '/docs/charts/parallel-coordinates', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Sunburst', to: '/docs/charts/sunburst', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Dendrogram', to: '/docs/charts/dendrogram', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Venn', to: '/docs/charts/venn', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Waffle', to: '/docs/charts/waffle', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Marimekko', to: '/docs/charts/marimekko', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Nightingale', to: '/docs/charts/nightingale', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Histogram', to: '/docs/charts/histogram', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Box plot', to: '/docs/charts/box-plot', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Violin', to: '/docs/charts/violin', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Ridgeline', to: '/docs/charts/ridgeline', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Beeswarm', to: '/docs/charts/beeswarm', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Population pyramid', to: '/docs/charts/population-pyramid', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Stream graph', to: '/docs/charts/stream-graph', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Bump', to: '/docs/charts/bump', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Gantt', to: '/docs/charts/gantt', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Horizon', to: '/docs/charts/horizon', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Sankey', to: '/docs/charts/sankey', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Chord', to: '/docs/charts/chord', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Network', to: '/docs/charts/network', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Tile map', to: '/docs/charts/tile-map', chip: 'NEW', sub: CHART_PAGE_SUB },
          { label: 'Word cloud', to: '/docs/charts/word-cloud', chip: 'NEW', sub: CHART_PAGE_SUB },
        ],
      },
      {
        title: 'Layout',
        items: [
          { label: 'Overview', to: '/components#layout' },
          item('Layout primitives', 'layout'),
        ],
      },
    ],
  },
  {
    title: 'Motion',
    items: [
      { label: 'Principles', to: '/docs/motion#four-rules' },
      { label: 'Tokens', to: '/docs/motion#anatomy' },
      { label: 'Choreography', to: '/docs/motion#write-once' },
      { label: 'Reduced motion', to: '/docs/motion#reduced' },
    ],
  },
  {
    title: 'Utilities',
    items: [
      { label: 'Presence', to: '/components/motion-utilities#presence' },
      { label: 'Stagger', to: '/components/motion-utilities#stagger' },
      { label: 'NumberFlow', to: '/components/motion-utilities#numberflow' },
      { label: 'useMotionPreference', to: '/components/motion-utilities#use-motion-preference' },
      { label: 'Overview', to: '/motion-utilities' },
    ],
  },
]

export function prevNext(slug: string): { prev?: ComponentEntry; next?: ComponentEntry } {
  const i = COMPONENTS.findIndex((c) => c.slug === slug)
  return { prev: COMPONENTS[i - 1], next: COMPONENTS[i + 1] }
}
